#!/bin/bash

# This script is intended to be sourced.
#
# It defines two variables:
# - `OVERSION`: the in-use Odoo version
# - `ORC_PATH`: the path of the `.odoorc` file
#
# To determine the relevant Odoo version (`OVERSION`), the script applies
# the following priority order:
#
# 1. `-o` option: If present, removes `-o` and its value from the main
#    script arguments and treats the value as the version
# 2. `GLOBAL_OVERSION` variable: If defined, uses it as the Odoo version
# 3. Regex match: Extracts the version from the first argument of the
#    main script, if applicable
# 4. External script: Calls the script `sv` (“(s)elect (v)ersion”) if
#    it exists and considers its output as the Odoo version
#    - The command `sv` is user-defined and therefore not included in
#      this tool
#    - All arguments of the main script are passed to `sv`
#    - The script name can be customized via `SV_SCRIPT_NAME`
# 5. Fallback: Uses the version `master`, or `FALLBACK_OVERSION` if
#    specified
#
# Finally, the script defines `ORC_PATH`. It first checks whether such
# a file exists in `$HOME/src/$OVERSION/.odoorc`. If not, it considers
# the case of a mono-version setup and looks for the file at:
# `$HOME/.odoorc`
# If no file is found, the variable remains unset.

version_rg="(master|(saas-)?[0-9]{2}\.[0-9])"

extract_version() {
  echo "$1" | grep -oE "$version_rg"
}

extract_version_strict() {
  echo "$1" | grep -oE "^$version_rg\$"
}

filtered_args=()
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -o)
      version_from_option="$2"
      shift 2
      ;;
    *)
      filtered_args+=("$1")
      shift
      ;;
  esac
done
# Redefine scripts arguments with all but `-o` and its value
set -- "${filtered_args[@]}"

script_name=${SV_SCRIPT_NAME:-"sv"}

version_from_arg=$(extract_version "$1")

if [ -n "$version_from_option" ]; then
  OVERSION=$version_from_option
elif [ -n "$GLOBAL_OVERSION" ]; then
  OVERSION=$GLOBAL_OVERSION
elif [ -n "$version_from_arg" ]; then
  OVERSION=$version_from_arg
elif command -v "$script_name" >/dev/null 2>&1; then
  OVERSION=$($script_name "$@")
fi

OVERSION=$(extract_version_strict "$OVERSION") # final check

if [ -z "$OVERSION" ]; then
  echo "No version found, defaulting to ${FALLBACK_OVERSION:-master}" >&2
  OVERSION="${FALLBACK_OVERSION:-master}"
fi

if [ -e "$HOME/.odoorc" ]; then
  ORC_PATH="$HOME/src/$OVERSION/.odoorc"
elif [ -e "$HOME/src/$OVERSION/.odoorc" ]; then
  ORC_PATH="$HOME/.odoorc"
fi
