#!/bin/bash 

function delete_dbs {
	for db in $@;
	do
		echo "Drop $db"
		dropdb --if-exists $db
	done
}

if [ $# -eq 0 ]
then
	echo "No arguments supplied"
	exit 1
fi

for arg in "$@";
do
	delete_dbs $(ldb | grep "$arg")
done
